<a href="https://colab.research.google.com/github/Imaspson/ML-Learning/blob/main/ML_Learning_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

arr = np.array([-1, 2, 5], dtype=np.float32)

print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


# NumPy Arrays

In [2]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]],
               dtype=np.float32)

print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


# Upcasting - if int and float are in an array, all elements are converted to float etc.

In [3]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


# Copying

In [4]:
a = np.array([0, 1])
b = np.array([9, 8])
c = a

print(f"Array a: {repr(a)}")
c[0] = 5
print(f"Array a: {repr(a)}")

d = b.copy()
d[0] = 6
print(f"Array b: {repr(b)}")

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


# Casting

In [5]:
arr = np.array([0, 1, 2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


# NaN

In [6]:
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

np.array([np.nan, 1, 2], dtype=np.float32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


array([nan,  1.,  2.], dtype=float32)

# Infinity

In [7]:
print(np.inf > 100000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

np.array([np.inf, 3], dtype=np.float32)

True
array([inf,  5.])
array([-inf,   1.])


array([inf,  3.], dtype=float32)

In [8]:
arr = np.array([np.nan, 2, 3, 4, 5],
               dtype=np.float32)
print(repr(arr))

arr2 = arr.copy()
arr2[0] = 10
print(repr(arr2))

array([nan,  2.,  3.,  4.,  5.], dtype=float32)
array([10.,  2.,  3.,  4.,  5.], dtype=float32)


# Ranged data

In [12]:
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [15]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


# Reshaping data

In [16]:
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print(f"New shape: {reshaped_arr.shape}")

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)


# Transposing

In [17]:
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)
print(repr(arr))
print(f"arr shape: {arr.shape}")
print(repr(transposed))
print(f"tarnsposed shape: {transposed.shape}")

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
tarnsposed shape: (2, 4)


In [18]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes=(1, 2, 0))

print(f"arr shape: {arr.shape}")
print(f"transposed shape: {transposed.shape}")

arr shape: (3, 4, 2)
transposed shape: (4, 2, 3)


# Zeros and Ones

In [21]:
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [22]:
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

array([[0, 0],
       [0, 0]])
